modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/samedifferent/morevillagers/issues"

[[mods]]
modId="morevillagers"
version="${version}"
displayName="More Villagers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/more-villagers"
logoFile="icon.png"
authors="SameButDifferent, Zero_DSRS_VX"
description='''
Adds new villager jobs, trades, and workstations!
'''

[[dependencies.morevillagers]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.morevillagers]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
